name: CI-CD Pipeline (Unittest Validator)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- 🔽 นี่คือ "หัวใจ" 🔽 ---
      # (ขั้นตอนนี้จะ "พัง" 🔴 ถ้า Logic ผิด)
      - name: 3. (Validation) Run Unit Tests
        run: python -m unittest test_app.py
      # --- 🔼 สิ้นสุดการแก้ไข 🔼 ---
        
      # --- ขั้นตอน 4-6 จะทำงาน "ต่อเมื่อ" ขั้น 3 (Sonar) "ผ่าน" 🟢 เท่านั้น ---

      - name: 4. Generate Build Number
        id: build_number
        run: echo "VERSION_NUMBER=1.0.$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
        
      - name: 5. Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 6. Build and Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gbelt/homework-2:${{ steps.build_number.outputs.VERSION_NUMBER }}
